version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: margaritapsw
      MYSQL_DATABASE: margaritabd
      MYSQL_USER: margaritauser
      MYSQL_PASSWORD: margaritapsw
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - mysql_network

volumes:
  mysql_data:

networks:
  mysql_network:
