spring:
  application:
    name: margaritaStore
  datasource:
    url: jdbc:mysql://localhost:3306/margaritabd
    username: margaritauser
    password: margaritapsw
    driver-class-name: com.mysql.cj.jdbc.Driver

